Repository CS2103-AY1819S1-W13-4/main, pull requests merged in 2018-11, with the labels that each got.

#157 Include edit paid test cases
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/test/java/seedu/address/logic/commands/PayCommandTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/PayCommandSystemTest.java
Labels: priority.High

#193 Fix invalid inputs in command line
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tuitiontiming/TuitionTiming.java
  src/test/data/XmlSerializableTutorHelperTest/duplicatePersonTutorHelper.xml
  src/test/data/XmlSerializableTutorHelperTest/invalidPersonTutorHelper.xml
  src/test/data/XmlSerializableTutorHelperTest/typicalPersonsTutorHelper.xml
  src/test/data/XmlTutorHelperStorageTest/invalidAndValidPersonTutorHelper.xml
  src/test/data/XmlTutorHelperStorageTest/invalidPersonTutorHelper.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/data/XmlUtilTest/validTutorHelper.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tuitiontiming/TuitionTimingTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: type.Bug

#195 Edit documentation and add assertions to sortByTime()
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/model/TutorHelper.java
  src/main/java/seedu/address/model/tuitiontiming/TuitionTiming.java
Labels: type.Bug

#197 Fixes to subject parsing and update to User Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/SusterDrifter.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/subject/SubjectType.java
Labels: severity.Medium, type.Bug

#198 Fix EditCommand replace Payment and update DeveloperGuide include remark for index
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug

#204 Update README.adoc
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/andlimey.adoc
Labels: priority.Low

#209 Update andlimey.adoc and add assertion to GroupCommand
  docs/team/andlimey.adoc
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/model/tuitiontiming/TuitionTimingContainsKeywordsPredicate.java
Labels: priority.Low

#210 Add Personal Portfolio Page, reformat AboutUs.adoc, fix typos
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/andlimey.adoc
  docs/team/lywjoel.adoc
  docs/team/ooihuiying.adoc
  docs/team/susterdrifter.adoc
Labels: priority.High, status.Ongoing, type.Task

#211 Complete Refactoring of AppendSyll / EraseSyll -> AddSyll / DeleteSyll, Build Fixes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/lywjoel.adoc
  docs/team/ooihuiying.adoc
  src/main/java/seedu/address/logic/commands/DeleteSyllCommand.java
  src/main/java/seedu/address/logic/parser/DeleteSyllCommandParser.java
  src/main/java/seedu/address/logic/parser/TutorHelperParser.java
  src/test/java/seedu/address/logic/parser/EarningsCommandParserTest.java
  src/test/java/systemtests/AddSyllCommandSystemTest.java
Labels: priority.Low, status.Ongoing, type.Bug

#212 Rework GUI
  src/main/java/seedu/address/model/subject/Subject.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/PersonDetail.css
  src/main/resources/view/PersonPage.css
Labels: priority.Low, type.Enhancement

#215 Refactor AddressBook to TutorHelper
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditSyllCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TutorHelper.java
  src/main/java/seedu/address/model/VersionedTutorHelper.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/subject/Syllabus.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddSubCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CopySubCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSubCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddSubCommandSystemTest.java
  src/test/java/systemtests/AddSyllCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/CopySubCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/DeleteSubCommandSystemTest.java
  src/test/java/systemtests/DeleteSyllCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/EditSyllCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/MarkCommandSystemTest.java
  src/test/java/systemtests/PayCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/TutorHelperSystemTest.java
Labels: priority.Medium, severity.Low, type.Bug

#221 Add values to SubjectType Enum, Update Subject Display, Fix Code Style Violations, Change Person Equality
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/subject/Subject.java
  src/main/java/seedu/address/model/subject/SubjectType.java
  src/main/java/seedu/address/model/subject/Syllabus.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/BrowserPanel.fxml
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.High, severity.Medium, status.Ongoing, type.Bug, type.Enhancement

#224 Fix UI bugs for editsyll/addsyll/deletesyll/mark/paid
  src/main/java/seedu/address/logic/commands/AddSyllCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSyllCommand.java
  src/main/java/seedu/address/logic/commands/EditSyllCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/BrowserPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/PayCommandTest.java
Labels: priority.High, type.Bug

#227 Update DeveloperGuide.adoc and UML Diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/DeletePersonSdForLogic.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SDforDeletePerson.png
  docs/images/SDforDeletePersonEventHandling.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
Labels: priority.High

#241 Fix Command Usage Messages, Fix Tests, Fix Typos
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddSubCommand.java
  src/main/java/seedu/address/logic/commands/AddSyllCommand.java
  src/main/java/seedu/address/logic/commands/CopySubCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSubCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSyllCommand.java
  src/main/java/seedu/address/logic/commands/EarningsCommand.java
  src/main/java/seedu/address/logic/commands/EditSyllCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/PayCommandSystemTest.java
Labels: priority.High, severity.Medium, type.Bug

#240 Fix to addsyll bug, Update UserGuide
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddSyllCommand.java
  src/test/java/seedu/address/logic/commands/AddSyllCommandTest.java
Labels: severity.Medium, type.Bug

#242 Update DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/GroupSequenceDiagram.pptx
  docs/images/GroupSequenceDiagram.png
  docs/images/GroupSequenceDiagramDay.png
  docs/images/GroupSequenceDiagramTime.png
Labels: priority.Low

#251 Update HelpWindow.html and ongyz.adoc
  docs/DeveloperGuide.adoc
  docs/team/ongyz.adoc
Labels: priority.Low, severity.Low

#259 Add Check before Loading Payments
  src/main/java/tutorhelper/storage/XmlSerializableTutorHelper.java
Labels: priority.Low, severity.Low, type.Bug

#261 Remove Redundant Files, Update Documentation and PPP
  copyright.txt
  docs/DeveloperGuide.adoc
  docs/images/LogicComponentSequenceDiagram.png
  docs/images/SeEduLogo.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/images/damithc.jpg
  docs/images/getting-started-ui-result-after.png
  docs/images/getting-started-ui-result-before.png
  docs/images/getting-started-ui-status-after.png
  docs/images/getting-started-ui-status-before.png
  docs/images/getting-started-ui-tag-after.png
  docs/images/getting-started-ui-tag-before.png
  docs/images/github_repo_settings.png
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  docs/team/johndoe.adoc
  docs/team/lywjoel.adoc
  src/main/resources/images/calendar.png
  src/main/resources/images/clock.png
  src/main/resources/images/fail.png
  src/main/resources/images/info_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonPage.html
  src/main/resources/view/default.html
Labels: priority.Low, status.Ongoing, type.Task

#263 Add Logging for loadStudentPage()
  docs/DeveloperGuide.adoc
  src/main/java/tutorhelper/ui/BrowserPanel.java
Labels: priority.Low, type.Enhancement

#274 Update Personal Portfolio Page, Add HelpWindow.html
  docs/team/lywjoel.adoc
  src/main/java/tutorhelper/logic/commands/EarningsCommand.java
  src/main/java/tutorhelper/storage/XmlAdaptedPay.java
  src/main/resources/docs/HelpWindow.html
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.Medium, type.Task
