Repository CS2103-AY1819S1-W13-4/main, pull requests merged in 2018-10, with the labels that each got.

#47 Documentation Updates
  README.adoc
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EarningsCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/logic/parser/EarningsCommandParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TuitionTiming.java
Labels: priority.Medium, type.Story

#46 Subject data is written into into storage file
  src/main/java/seedu/address/model/subject/Subject.java
  src/main/java/seedu/address/model/subject/Syllabus.java
  src/main/java/seedu/address/storage/XmlAdaptedSubject.java
  src/main/java/seedu/address/storage/XmlAdaptedSyllabus.java
Labels: priority.Medium, type.Task

#62 Change 'rmtodo' to 'erasesyll', 'todo' to 'appendsyll'
  src/main/java/seedu/address/logic/commands/AppendSyllCommand.java
  src/main/java/seedu/address/logic/commands/EraseSyllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AppendSyllCommandParser.java
  src/main/java/seedu/address/logic/parser/EraseSyllCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/model/subject/Subject.java
Labels: priority.Low, severity.Medium, type.Enhancement

#74 Fix some test cases involving Person
  src/main/java/seedu/address/model/person/TuitionTiming.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.Medium, severity.Medium

#73 Payment can be edited with paid
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/TuitionTiming.java
Labels: priority.Medium, status.Ongoing

#75 Correct errors in test cases
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug

#78 Add GUI display for subjects, update User Guide, fix bugs
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AppendSyllCommand.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/model/subject/Subject.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.html
  src/main/resources/view/PersonPage.html
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.Medium, type.Bug, type.Enhancement, type.Task

#87 Add documentation to Developer Guide, fix code style
  docs/DeveloperGuide.adoc
  docs/diagrams/AddSubSequenceDiagram.pptx
  docs/diagrams/DeleteSubSequenceDiagram.pptx
  docs/images/AddSubSequenceDiagram.png
  docs/images/DeleteSubSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tuitionTiming/TuitionTiming.java
  src/main/java/seedu/address/model/tuitionTiming/TuitionTimingContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
Labels: priority.High, status.Ongoing, type.Bug, type.Enhancement

#93 Add GUI support for tuition timing, fix import statements
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/PersonPage.html
Labels: priority.High, type.Bug, type.Enhancement

#99 Stylised the person panel
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/PersonPage.css
  src/main/resources/view/PersonPage.html
Labels: priority.Medium, type.Enhancement

#100 Appendsyll and copysub includes duplicate check to prevent duplicate syllabus
  src/main/java/seedu/address/logic/commands/AppendSyllCommand.java
  src/main/java/seedu/address/model/subject/Subject.java
  src/main/java/seedu/address/model/subject/Syllabus.java
Labels: priority.Low, type.Bug

#101 Update DeveloperGuide and UserGuide to include duplicate checking
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Low

#103 Update DeveloperGuide.adoc fix sequence diagram heading for Payment Edit
  docs/DeveloperGuide.adoc
Labels: priority.Low

#112 Add addsub and deletesub commands, minor bug fixes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddSubCommand.java
  src/main/java/seedu/address/logic/commands/AppendSyllCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSubCommand.java
  src/main/java/seedu/address/logic/commands/EraseSyllCommand.java
  src/main/java/seedu/address/logic/parser/AddSubCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AppendSyllCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteSubCommandParser.java
Labels: priority.High, status.Ongoing, type.Bug, type.Enhancement

#109 Refine Group Command to sort based on day or time after filtering the list
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/tuitiontiming/TuitionTiming.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium, severity.Medium, type.Story, type.Task

#115 Update documentation for addsub / deletesub
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/DeleteSubCommand.java
Labels: priority.Medium, status.Ongoing, type.Bug

#121 Add EditSyllCommand: edits syllabus entries directly
  src/main/java/seedu/address/logic/commands/EditSyllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditSyllCommandParser.java
  src/main/java/seedu/address/model/subject/Subject.java
Labels: priority.High, type.Enhancement

#126 Fix XmlAdaptedPay/XmlUtilTest/EditPersonDecriptorTest and XML files
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/XmlAdaptedPay.java
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, severity.High, status.Ongoing, type.Bug

#132 Fix test cases
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/guitests/GuiRobot.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.High, status.Ongoing, type.Bug

#131 Fix XmlSerializableAddressBookTest
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
Labels: type.Bug

#144 Add tests for GroupCommandParserTest
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/model/tuitiontiming/TuitionTimingContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
Labels: priority.Low

#145 Add GroupCommandTest and fix errors
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/model/tuitiontiming/TuitionTimingContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AppendSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/systemtests/CopySubCommandSystemTest.java
Labels: priority.Low, type.Bug

#149 Add EditSyllCommandSystemTest and fix EditCommandSystemTest
  src/main/java/seedu/address/logic/commands/EditSyllCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlSerializableTutorHelperTest/typicalPersonsTutorHelper.xml
  src/test/data/XmlTutorHelperStorageTest/NotXmlFormatTutorHelper.xml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/seedu/address/logic/commands/AppendSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditSyllCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/CopySubCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/EditSyllCommandSystemTest.java
  src/test/java/systemtests/TutorHelperSystemTest.java
Labels: priority.Medium

#150 Update README.adoc: update appveyor
  README.adoc
Labels: priority.Low

#152 Add GroupCommandSystemTest and Update README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/systemtests/GroupCommandSystemTest.java
Labels: priority.Medium

#151 Add AppendSyllCommandSystemTest and SubjectsUtilTest
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditSyllCommandTest.java
  src/test/java/seedu/address/logic/parser/EditSyllCommandParserTest.java
  src/test/java/seedu/address/model/util/SubjectsUtilTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AppendSyllCommandSystemTest.java
  src/test/java/systemtests/EditSyllCommandSystemTest.java
  src/test/java/systemtests/TutorHelperSystemTest.java
Labels: priority.Medium
